### ISSUE TITLE
Unable to load Maven meta-data from https://jcenter.bintray.com/com/bugfender/sdk/android/maven-metadata.xml.

### ISSUE THREAD

**Issue by zhida97** [bugfender/BugfenderSDK-Flutter#29]
My setup:
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip (tried upgraded to 7.2 but still failing)
flutter_bugfender: ^2.0.1 (tried upgraded to 2.1.0 but still failing)

[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19045.2130], locale en-SG)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.72.2)
[√] Connected device (3 available)

More logs:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.bugfender.sdk:android:3.+.
     Required by:
         project :app > project :flutter_bugfender
      > Failed to list versions for com.bugfender.sdk:android.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/bugfender/sdk/android/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/bugfender/sdk/android/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/bugfender/sdk/android/maven-metadata.xml'.
                  > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 42s
Running Gradle task 'assembleDebug'...                            103.5s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...

**Comment by shilangyu** [comment]
Can confirm this happening to me as well. Probably will resolve itself within a few hours, but would be nice if bugfender would migrate away from jcenter (I thought this was the case already?)

**Comment by Ruon1s** [comment]
I also was on version 2.0.1 and upgraded into 2.1.0 with no luck. The package is still trying to load from deprecated jcenter.bintray

**Comment by madura7** [comment]
this happens to me as well. is there any workaround till it fixes?

**Comment by shilangyu** [comment]
Local workaround, add this to your `app/build.gradle`'s `dependencies` block:

```gradle
implementation('com.bugfender.sdk:android') {
    version {
        strictly '3.0.16'
    }
}
```

**Comment by tenhobi** [comment]
Looks like it works now ok. :)

**Comment by zhida97** [comment]
It is working now on my end without applying any fixes, I will close this issue. Big thanks for the temporary workaround and everyone for looking into this.

**Comment by shilangyu** [comment]
I dont think this should be closed. This issue was not resolved, it will come back the next time jcenter decides to break.

**Comment by jgimenez** [comment]
Hi there, first of all, thanks everyone for contributing your workarounds!

We will look into removing the jcenter dependency if possible. However, the internet sometimes breaks, and there's little we can do about it. If we remove the dependency from jcenter we will merely shift to depend on something else, and then we might have this issue again, but for a different provider. Anyway, we'll research if there's a better option than jcenter, and migrate if possible.

**Comment by shilangyu** [comment]
@jgimenez while I overall agree with what you said (changing providers doesn't really help since outages are still out of your control), this situation is special. Jcenter has been deprecated for a while now and the ecosystem has been transitioning to other provides (largely to Maven Central). From experience, I don't remember a single instance when Maven Central was down. On the other hand, jcenter being down has affected my work many times. Especially since it's down for many hours, blocking the CD pipeline completely for a full day. While local workarounds are good and they work, I would be very reluctant to push such a change to fix the CD.

Technically speaking, it seams this plugin has migrated over to `mavenCentral` a long time ago ([see here](https://github.com/bugfender/BugfenderSDK-Flutter/pull/20)) and the android bugfender sdk is on maven central ([see here](https://mvnrepository.com/artifact/com.bugfender.sdk/android)). So I have no idea why this plugin was pulling the version from jcenter and why specifying the exact version fixed it (dependency is declared [here](https://github.com/bugfender/BugfenderSDK-Flutter/blob/d5d76048ab7e3cd145a091977aa49e581f3e2d9b/android/build.gradle#L40)). That is why I would argue that this issue should be reopened and marked as a bug, since this behavior is clearly not expected.

**Comment by jgimenez** [comment]
Hi there, it looks like our plugin does not use JCenter at all. Instead, Flutter was using JCenter until version 2.8.0. We recommend upgrading your Flutter SDK to resolve the issue.

**Comment by shilangyu** [comment]
Hello again. Sorry for coming back to complain, but: Our project uses flutter 3.3.x, and yet we encountered this problem.

**Comment by jgimenez** [comment]
You can see here we do not declare a dependency with jcenter: https://github.com/bugfender/BugfenderSDK-Flutter/blob/master/android/build.gradle
